using System;
using System.Collections.Generic;
using Lexy.Compiler.Generation.CSharp.FunctionCalls;
using Lexy.Compiler.Infrastructure;
using Lexy.Compiler.Language.Expressions.Functions;
using Lexy.RunTime;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Lexy.Compiler.Generation.CSharp.ExpressionStatements;

//A lexy function is called without assignment (at statement level) which means it should auto map it's results and parameters
//Otherwise LexyFunctionCallExpression's syntax is generated by LexyFunctionCall
//Syntax: "LexyFunction()"
internal static class AutoMapLexyFunctionStatement
{
    public static bool Matches(LexyFunctionCallExpression expression)
    {
        if (expression.FunctionCall is not AutoMapLexyFunctionCall)
        {
            throw new InvalidOperationException("AutoMap should be set to true for a statement.");
        }
        return true;
    }

    public static IEnumerable<StatementSyntax> Create(LexyFunctionCallExpression expression)
    {
        Assert.NotNull(expression, nameof(expression));

        var functionCall = Assert.Is<AutoMapLexyFunctionCall>(expression.FunctionCall, "expression.FunctionCall");
        var parameterVariable = $"{LexyCodeConstants.ParameterVariable}_{expression.Reference.LineNumber}";
        var resultsVariable = $"{LexyCodeConstants.ResultsVariable}_{expression.Reference.LineNumber}";

        var result = new List<StatementSyntax>();

        result.AddRange(FillFunctionStatement.FillStatementSyntax(
            parameterVariable,
            functionCall.ParametersType,
            functionCall.MappingParameters));

        result.Add(RunFunction(expression, functionCall, parameterVariable, resultsVariable));

        result.AddRange(ExtractFunctionStatement.ExtractStatementSyntax(
            functionCall.MappingResults,
            resultsVariable));

        return result;
    }

    private static StatementSyntax RunFunction(LexyFunctionCallExpression expression, AutoMapLexyFunctionCall functionCall, string parameterVariable,
        string resultsVariable)
    {
        var initialize = LexyFunctionCallSyntax.RunFunction(expression.FunctionName, parameterVariable);

        var variable = VariableDeclarator(Identifier(resultsVariable))
            .WithInitializer(EqualsValueClause(initialize));

        return LocalDeclarationStatement(
            VariableDeclaration(Types.Syntax(functionCall.ResultsType))
                .WithVariables(SingletonSeparatedList(variable)));
    }
}