using System.Collections.Generic;
using Lexy.Compiler.Generation.CSharp.Syntax;
using Lexy.Compiler.Language.Expressions;
using Lexy.RunTime;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Lexy.Compiler.Generation.CSharp.ExpressionStatements;

//A lexy function is called with a spread operator assignment (at statement level) which means it should auto map it's results
//Otherwise LexyFunctionCallExpression's syntax is generated by LexyFunctionCall
//Syntax: "... = LexyFunction( xxx )"
internal static class AutoMapLexyFunctionStatement
{
    public static bool Matches(SpreadAssignmentExpression expression) => true;

    public static IEnumerable<StatementSyntax> Create(SpreadAssignmentExpression expression)
    {
        Assert.NotNull(expression, nameof(expression));

        var resultsVariable = $"{LexyCodeConstants.ResultsVariable}_{expression.Reference.LineNumber}";

        var result = new List<StatementSyntax>
        {
            RunFunction(expression, resultsVariable)
        };

        result.AddRange(ExtractFunctionStatement.ExtractStatementSyntax(
            expression.Mapping,
            resultsVariable));

        return result;
    }

    private static StatementSyntax RunFunction(SpreadAssignmentExpression expression, string resultsVariable)
    {
        var initialize = Expressions.ExpressionSyntax(expression.Assignment);

        var variable = VariableDeclarator(Identifier(resultsVariable))
            .WithInitializer(EqualsValueClause(initialize));

        return LocalDeclarationStatement(
            VariableDeclaration(Types.Syntax(expression.Mapping.MappingType))
                .WithVariables(SingletonSeparatedList(variable)));
    }
}